### ISSUE TITLE
dsnparse 0.2.0 breaks compatibility for usernames with '@'

### ISSUE THREAD

**Issue by daveboutcher** [Jaymon/dsnparse#11]
Previously dsnparse handled:
```
pydb://user@database:password@mysystem.com:9090/system
```
Now it throws an exception parsing that.  I realise users should be URL encoded, but there are existing implemenations where they are not

**Comment by Jaymon** [comment]
Yup, sorry about that. I tried everything to keep backwards compatibility but I couldn't get all the tests to pass with the new functionality I needed.

The good news is previous versions are pretty stable, so if you don't need any of the new functionality, just peg your version to `0.1.15`:

```
dsnparse==0.1.15
```
