### ISSUE TITLE
Postgres connection strings

### ISSUE THREAD

**Issue by Jaymon** [Jaymon/dsnparse#3]
Postgres allows strings like:

    postgresql:///mydb?host=localhost&port=5433

[via](https://www.postgresql.org/docs/9.2/static/libpq-connect.html#LIBPQ-CONNSTRING)

So it might be worth adding support for passing things like `host`, and `username`, etc. in as query params.

**Comment by vitaly-t** [comment]
There is also [connection-string](https://github.com/vitaly-t/connection-string), with complete syntax support ;)
